name: rtAtten
channels:
  - defaults
  - conda-forge
  - brainiak
dependencies:
  - cython
  - pybind11
  - numpy
  - scipy
  - scikit-learn
  - pydicom
  - toml
  - watchdog
  - ipython
  - jupyter
  - pytest
  - flake8
  - mypy
  - brainiak

