[experiment]
experimentName = "rtAttenPenn"
experimentId = 2
model = "rtAtten"

[session]
rtData = 0
sessionId = "20180220T112725"
subjectName = "subject1"
subjectNum = 1
subjectDay = 1
dataDir = "data/"
imgDir = "data/img"
serverDataDir = "data/server"
findNewestPatterns = 1
watchFilePattern = "*.dcm"
dicomNamePattern = "001_0000{}_000{}.dcm"
minExpectedDicomSize = 300000
legacyRun1Phase2Mode = 0
sliceDim = 64
cutoff = 112
FWHM = 5
retrieveServerFiles = 0
patternsDesignFiles = ["patternsdesign_1_20180105T000000.mat", "patternsdesign_2_20180105T000000.mat", "patternsdesign_3_20180105T000000.mat"]
## !Below here! --> Fields for replaying already collected data ##
Runs = [1, 2, 3]
ScanNums = [11, 13, 15]
validate = 1
replayMatFileMode = 1  # set to 1 for replay mode, will use validationData to replay
validationModels = ["trainedModel_1_20180105T_1048.mat", "trainedModel_2_20180105T_1049.mat", "trainedModel_3_20180105T_1049.mat"]
validationData = ["patternsdata_1_20180105T_1048.mat", "patternsdata_2_20180105T_1049.mat", "patternsdata_3_20180105T_1049.mat"]
# validationModels = ["trainedModel_1_20180208T105318_py0.mat", "trainedModel_2_20180208T105401_py0.mat", "trainedModel_3_20180208T105443_py0.mat"]
# validationData = ["patternsdata_1_20180208T105318_py0.mat", "patternsdata_2_20180208T105401_py0.mat", "patternsdata_3_20180208T105443_py0.mat"]
