[experiment]
experimentName = "rtAttenPenn"
experimentId = 2
model = "rtAtten"

[session]
subjectName = "subject1"
subjectNum = 1
subjectDay = 1
workingDir = "cwd"
inputDataDir = "data/input"
outputDataDir = "data/output"
imgDirHeader = "data/img"
findNewestPatterns = 1
patternsDesignFiles = ["patternsdesign_1_20180105T000000.mat", "patternsdesign_2_20180105T000000.mat", "patternsdesign_3_20180105T000000.mat"]
replayFiles = ["patternsdata_1_20180208T105318_py0.mat", "patternsdata_2_20180208T105401_py0.mat", "patternsdata_3_20180208T105443_py0.mat"]
validationModels = ["trainedModel_1_20180208T105318_py0.mat", "trainedModel_2_20180208T105401_py0.mat", "trainedModel_3_20180208T105443_py0.mat"]
watchFilePattern = "*.dcm"
dicomNamePattern = "001_0000{}_000{}.dcm"
minExpectedDicomSize = 300000
legacyRun1Phase2Mode = 0
sliceDim = 64
cutoff = 112
FWHM = 5
numRuns = 3
validate = 0
replayMode = 1
