[experiment]
model = "rtAtten"

[session]
experimentName = "rtAttenPenn"
experimentId = 1
subjectName = "subject1"
subjectNum = 1
subjectDay = 1
sessionId = "20180115T000000"
workingDir = "cwd"
inputDataDir = "data/input"
outputDataDir = "data/output"
imgDirHeader = "/tmp/rtAtten/img"
replayMode = 1
validate = 1
legacyRun1Phase2Mode = 0
patternsDesignFiles = ["patternsdesign_1_20180105T000000.mat", "patternsdesign_2_20180105T000000.mat", "patternsdesign_3_20180105T000000.mat"]
replayFiles = ["patternsdata_1_20180208T105318_py0.mat", "patternsdata_2_20180208T105401_py0.mat", "patternsdata_3_20180208T105443_py0.mat"]
validationModels = ["trainedModel_1_20180208T105318_py0.mat", "trainedModel_2_20180208T105401_py0.mat", "trainedModel_3_20180208T105443_py0.mat"]
