[experiment]
experimentName = "rtAttenPenn"
experimentId = 2
model = "rtAtten"

[session]
rtData = true
date = "2018-03-01"  # i.e. "2018-03-01" or "03/01/2018" or "today" or "now" etc.
sessionId = "20180310T123000"
subjectName = "0301181_rtAttenPenn"
subjectNum = 7
subjectDay = 1
dataDir = "data/"
imgDir = "data/img"
buildImgPath = true
serverDataDir = "data/server"
findNewestPatterns = true
watchFilePattern = "*.dcm"
dicomNamePattern = "001_0000{}_000{}.dcm"
minExpectedDicomSize = 300000
legacyRun1Phase2Mode = true
retrieveServerFiles = false
skipConfirmForReprocess = false
enforceDeadlines = false
calcClockSkewIters = 30
sliceDim = 64
cutoff = 200
FWHM = 5
Runs = [1, 2, 3]
ScanNums = [11, 13, 15]
## !Below here! --> Fields for replaying already collected data ##
replayMatFileMode = false  # will use validationData[] mat files to replay
validate = false
patternsDesignFiles = ["patternsdesign_1_20180105T000000.mat", "patternsdesign_2_20180105T000000.mat", "patternsdesign_3_20180105T000000.mat"]
validationData = ["patternsdata_1_20180105T_1048.mat", "patternsdata_2_20180105T_1049.mat", "patternsdata_3_20180105T_1049.mat"]
validationModels = ["trainedModel_1_20180105T_1048.mat", "trainedModel_2_20180105T_1049.mat", "trainedModel_3_20180105T_1049.mat"]
